<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property string $name
 * @property string $price
 * @property int $created_at
 */
class Product extends \yii\db\ActiveRecord
{
    public $scenario;
    const SCENARIO_CREATE ='create';
    const SCENARIO_UPDATE='update';
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'created_at'], 'required'],
            [['price'],'required', 'on' => self::SCENARIO_UPDATE],
            [['created_at'], 'integer'],
            [['name'], 'string', 'max' => 20],
            [['name'],'filter','filter'=>function($value){
                return trim(strip_tags($value));}],
            [['price'],'integer','min'=>1,'max'=>1000],
            [['price'],'default','value' => 0,'on'=>self::SCENARIO_CREATE]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'price' => 'Price',
            'created_at' => 'Created At',
        ];
    }
    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        $scenarios=parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios[self::SCENARIO_CREATE]=['name','price','created_at'];
        $scenarios[self::SCENARIO_UPDATE]=['price'];
        return $scenarios;
    }
}
